prompt:
  - text: ""
    fg: "white"
    bg: "reset"
  - text: "{user}@{host}"
    fg: "black"
    bg: "white"
  - text: ""
    fg: "white"
    bg: "blue"
  - text: "{cwd}"
    fg: "bright_white"
    bg: "blue"
  - text: " "
    fg: "blue"
    bg: "reset"

